### PR TITLE
fix:added some validation

### PR DESCRIPTION
**Pull request by Paribesh01**
Screenshot 2024-09-17 231749
Screenshot 2024-09-17 231814

added red box when field are empty
and centered the post button

https://github.com/user-attachments/assets/690e6c50-e74a-4da9-aa54-ff3f37640a4e

- #354

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
can you give a video to ref your changes ?

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code done

**Comment by VineeTagarwaL-code** [comment]
reviewing and testing now

**Comment by VineeTagarwaL-code** [comment]
this doesnt give the error message, please add that so i can merge

**Comment by Paribesh01** [comment]
Screenshot 2024-09-21 142144
added error message

**Comment by VineeTagarwaL-code** [comment]
the red color is not so visible, can you improve over that ?

**Comment by Paribesh01** [comment]
Screenshot 2024-09-21 145931
@VineeTagarwaL-code done

**Pull request merged**
