### PR TITLE
contact form added

### PR DESCRIPTION
**Pull request by yash-kh**
What does this PR do?
#141 

Created Contact Form

Action added:
submitContactForm, getContactFormSubmissions

Component Created:
ContactForm, Textarea

Schema added:
ContactFormSubmission

contact-us set to publicRoute

What more can be done:
1 - View for ADMIN
2 - Optional images, setup for S3 or any other storage.

Will start work on the rest after this PR resolves.

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
Where is the video reference for this pr ?

**Comment by yash-kh** [comment]
https://github.com/user-attachments/assets/e7c7eff9-c880-4369-8215-48ff8cc05e05

@VineeTagarwaL-code Here

**Comment by yash-kh** [comment]
Was waiting for the approval so that I can work on these:
1 - View for ADMIN
2 - Optional images, setup for S3 or any other storage.

**Comment by VineeTagarwaL-code** [comment]
Quick Question: 

1.  How & Where are you  sending this messages after submit is clicked ?

**Comment by yash-kh** [comment]
Just stored in the DB for now, what do you suggest, i was thinking to make a view where admin can see them or make a mailer queue which will forward it to admins mail address.

**Comment by VineeTagarwaL-code** [comment]
i dont think storing in the db is good option at all

**Comment by yash-kh** [comment]
What do you suggest?

**Comment by VineeTagarwaL-code** [comment]
will think about this and come back to you soon

**Comment by VineeTagarwaL-code** [comment]
will open a issue on this soon, for now we ahve to see what smtp provider we have to use

**Comment by yash-kh** [comment]
@VineeTagarwaL-code Cool please, assign it to me will pick it up right away.

**Pull request closed without merging**
