### PR TITLE
fix: added docker improvement

### PR DESCRIPTION
**Pull request by nolostra**
fix: #170

### CODE REVIEW

**Comment by pawann-2000** [comment]
Please explain the changes made.

**Comment by nolostra** [comment]
Separate package installation: By copying package*.json and running npm install before copying the rest of the application code, we ensure that this layer is cached effectively.
Ensure Prisma migrations: If Prisma migrations need to be applied at runtime, you may need to add a script or command to the CMD in the production stage to ensure the database is up-to-date. since we dont have prisma migration at currently needed 

if required : CMD ["sh", "-c", "npx prisma migrate deploy && npm run start"]



overall it is done for optimisation of docker file

**Comment by pawann-2000** [comment]
I'm sorry, the code that's present and the explanation given are not matching, can you please elaborate what you are trying to do here?

Let me explain my code:
- Caching is already implemented for the node_modules and .next folders, it's done using volumes.
- Prisma migrations are not yet implemented for a reason, there are no schema changes and production staging is still in discussion.

**Comment by nolostra** [comment]
bhai kya bolu ? u want to suck balls ?

**Comment by VineeTagarwaL-code** [comment]
@nolostra any kind of immature behaviour will lead to you getting banned from contributing to this repo in future

**Pull request closed without merging**
