### PR TITLE
Added JobPage and job PlaceHolders

### PR DESCRIPTION
**Pull request by zakiabdullahi**
addd jobId Page and job placeholder seed 

Screenshot 2024-08-06 222018
Screenshot 2024-08-06 222059

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
add a video / image to show what you changed exactly, without and conflict resolution PR wont get merged

**Comment by zakiabdullahi** [comment]
@VineeTagarwaL-code  i have added

**Comment by VineeTagarwaL-code** [comment]
1. fix the conflicts
2. fix the jobid page ui, it appear over the footer

**Comment by zakiabdullahi** [comment]
@VineeTagarwaL-code fixed it  [PR](https://github.com/code100x/job-board/pull/52)

**Comment by VineeTagarwaL-code** [comment]
looks good but there are other people doing the same thing via hover, will look over it soon sure enough by that time can you check https://github.com/code100x/job-board/issues/137

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that

**Pull request closed without merging**
