### PR TITLE
adds dockerfile

### LINKED ISSUE #27: 📦 [FEATURE]: add docker file for the project
We need to add a docker file for the project, which will help contributors to setup this project locally without any hassle

### PR DESCRIPTION
**Pull request by Mishragini**
[feat]: add docker file
Fixes #27

### CODE REVIEW

**Review by pawann-2000 — CHANGES_REQUESTED** [review]
FROM node:18-alpine _it's better if we use node 20_

RUN npm install --ignore-scripts _this line is ignoring scripts, which is essential_

RUN apk add --no-cache openssl _we might not need this because alpine container contains openssl by default_

docker run -p 3000:3000 --env-file .env job-board _This might not be a good dev experience to pass args and run docker_

**Review by VineeTagarwaL-code — APPROVED** [review]
sounds good, will test it out first

**Comment by VineeTagarwaL-code** [comment]
Dont copy .env, we can use the --env-file flag in docker .. here how it will look without the .env

```shell
 # Use an official Node runtime as the base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy Prisma schema files
COPY prisma ./prisma/

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build the Next.js application
RUN npm run build

# Add Prisma CLI and ts-node to the PATH
ENV PATH /app/node_modules/.bin:$PATH

# Expose the port the app runs on
EXPOSE 3000

# The command will be overridden by docker-compose
CMD ["npm", "run", "start"]
```

**Review by VineeTagarwaL-code — CHANGES_REQUESTED** [review]
remove the mentioned thing

**Comment by Mishragini** [comment]
Made the requested changes in the current commit . Kindly review!

**Review by VineeTagarwaL-code — APPROVED** [review]

**Pull request merged**
