### PR TITLE
multistep-form

### LINKED ISSUE #484: 🚀 Feature:  candidate onboarding
### 🔖 Feature description

We need to take basic info about the candidate and save in our database 

things needed 

1. experience 
2. projects 
3. skills
4. resume 

Things needed for every point above is mentioned below in this picture

all the feature should implemented after the first time user signs up for us, sort of "onboarding"
image

flow needed : - 

image

https://mui.com/material-ui/react-stepper/ - use this for multipart form ( vertical stepper is a very good choice ) 

### 🎤 Why is this feature needed ?

for for onboarding

### ✌️ How do you aim to achieve this?

by os

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
fixes #484 

- used material-UI stepper to make a multi-step form from user onboarding
- changed the Prisma schema to add new Details

https://github.com/user-attachments/assets/67f0dec3-8e76-4ac8-bb72-04bcc535d042

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
:exploding_head: cleannnnnn

**Comment by VineeTagarwaL-code** [comment]
the build failed, correct that, also show the db getting updated with all the info, add resume and more skills 

make sure you show all of that in the manage profile page, no edit configuration needed in this pr just show them

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code , fixed the build issue and updated the profile section, here's the video link

https://drive.google.com/file/d/1M7R86MNXRdZS3CdR7eaNtMILgHBvaYEZ/view?usp=sharing

for some reason, my BunnyCDN config was not working, I will try to fix it and send another video with uploading resume . rest everything is working.

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code 

Uploading Screen Recording 2024-10-12 at 3.37.14 PM.mov…

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code 


https://github.com/user-attachments/assets/d16126a1-badf-42a2-97ca-69315ded0878

**Comment by VineeTagarwaL-code** [comment]
well done

add validation for github and project link
add loaders inside the buttons

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code, on it.
I will add an endpoint to validate GitHub, how can I validate the Project Link?

**Comment by VineeTagarwaL-code** [comment]
Just add a validation if it's an actual url or not and not some random text 

Check for https://, if it's http don't allow

**Comment by VineeTagarwaL-code** [comment]
is it done ?

**Comment by Ashutoshpadhi629** [comment]
Sorry for the delay . Will complete this today. @VineeTagarwaL-code

**Comment by Ashutoshpadhi629** [comment]
# Loaders
https://github.com/user-attachments/assets/b8479753-4f40-460f-ad5f-9fc3ed2270a7

# Only accepts valid Github Links and https Reqs
https://github.com/user-attachments/assets/ae40c6d8-92db-45bc-a9a4-acf1a26fead5

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code , can you review this , 
also, we are only accepting PDFs for resumes . is that okay?

**Comment by VineeTagarwaL-code** [comment]
Post on x and let everyone know you got your pr merged here

do tag @vineetwts and kirat bhayiya, 100xDevs on top !

**Comment by VineeTagarwaL-code** [comment]
bounty $150

**Comment by Ashutoshpadhi629** [comment]
> bounty $150

thank you so much, @VineeTagarwaL-code 🚀
100xDevs on top !

**Comment by VineeTagarwaL-code** [comment]
Make sure you post on x, good work !

**Pull request merged**
