### PR TITLE
Feat: Added the checks before deleting account

### LINKED ISSUE #512: 🚀 Feature: Verify Before Deleting Account
### 🔖 Feature description

So whenever user opens the delete account modal then he/she will be first prompted to enter few random text and only when user enter  same text, will be able to delete their account otherwise it delete button will be disabled

Screenshot from 2024-10-18 00-14-28

### 🎤 Why is this feature needed ?

This helps in ensuring that user is fully aware of what he/she is doing and also the longer the step for account deletion , more difficult for user to take decision

### ✌️ How do you aim to achieve this?

I will generate random text and when the input fields change then i will verify if they are same and if they are same then only enabling the delete button

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Kashyap1ankit**
closes #512 

[Screencast from 2024-10-18 01-24-22.webm](https://github.com/user-attachments/assets/a126bc41-0aa8-494f-b109-9fbd5f245904)

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
nice addition

**Review by VineeTagarwaL-code — APPROVED** [review]

**Comment by VineeTagarwaL-code** [comment]
image


cross button doesnt wroks 
light theme is bugged
fix these

**Comment by Kashyap1ankit** [comment]
Screenshot from 2024-10-19 22-43-34

@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
Have a better ui for the text, you can put in an embed like discord does when we use ```

**Comment by Kashyap1ankit** [comment]
Screenshot from 2024-10-19 23-54-56

Screenshot from 2024-10-19 23-55-50


@VineeTagarwaL-code is this good?

**Comment by Kashyap1ankit** [comment]
done @VineeTagarwaL-code 

[Screencast from 2024-10-20 00-45-13.webm](https://github.com/user-attachments/assets/4321f5f2-fa22-4aa2-9f69-744a2305f248)

**Comment by VineeTagarwaL-code** [comment]
make sure you tag me and 100xdev in your post, lg !!!

**Comment by Kashyap1ankit** [comment]
> make sure you tag me and 100xdev in your post, lg !!!

sure

**Pull request merged**
