### PR TITLE
feat: conditionally render Clear Filters button

### LINKED ISSUE #488: 🚀 Feature: Conditionally render Clear Filters button based on filter selection
### 🔖 Feature description

Add conditional rendering for the Clear Filters button in the JobFilters component. The button should only appear when at least one filter is selected, improving the user interface and reducing clutter.

### 🎤 Why is this feature needed ?

Currently, the Clear Filters button is always visible, even when no filters are selected. This can lead to a cluttered interface and potential user confusion. By only showing the button when filters are active, we can improve the user experience by:

1. Reducing visual noise when no filters are applied
2. Providing a clear indication that filters are in use
3. Offering an easy way to reset filters only when necessary

This change will make the job search interface cleaner and more intuitive for users.

### ✌️ How do you aim to achieve this?

1. Create a new custom hook called `useFilterCheck` to determine if any filters are selected
2. Update the JobFilters component to use this new hook
3. Modify the rendering of the Clear Filters button to be conditional based on the hook's output

The implementation will involve:
- Creating a new TypeScript file for the `useFilterCheck` hook
- Updating the JobFilters component to import and use the new hook
- Using conditional rendering to show/hide the Clear Filters button

### 🔄️ Additional Information

An alternative approach could be to disable the Clear Filters button when no filters are selected, rather than hiding it completely. However, hiding the button when it's not needed provides a cleaner interface and is more aligned with modern UI practices.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Ahmadmidlaj**
feat: conditionally render Clear Filters button based on filter selection

Closes #488

### CODE REVIEW

**Comment by mrsamirr** [comment]
please provide screenshot or recorded video of this feature

**Comment by Ahmadmidlaj** [comment]
> please provide screenshot or recorded video of this feature


https://github.com/user-attachments/assets/5e68af32-a29d-46d1-aa69-a33f06ce828a

-it just displays clear filters button only if any filters are selected, or else button will not be shown.

**Comment by Ahmadmidlaj** [comment]
> please provide screenshot or recorded video of this feature

do u need any other information related to this? if yes please let me know

**Comment by Ahmadmidlaj** [comment]
@VineeTagarwaL-code please review this

**Pull request merged**
