### PR TITLE
Refactor UI and code optimization

### PR DESCRIPTION
**Pull request by Harit007x**

### CODE REVIEW

**Comment by Harit007x** [comment]
https://github.com/user-attachments/assets/10a936e6-cefd-454f-a1b4-8504dbdfbd30

Covered these changes :
- [x] Replaced static tailwind vars with theme compatible vars
- [x] Refactored Login Page UI
- [x] Improvised styles and code for siteheader, navbar and mobile nav
- [x] Created a Logo component instead of using copy pasting same code multiple times
- [x] Replaced normal lucide imports with Icon component for better code pratices
- [x] Removed unwated useState updates after login that was causing error

**Comment by VineeTagarwaL-code** [comment]
https://github.com/code100x/job-board/issues/137 look at this and only ask to be assigned first, the present solution of yours has many flaws

**Comment by Harit007x** [comment]
> #137 look at this and only ask to be assigned first, the present solution of yours has many flaws

Just asking for learning purposes, could you state what kind of flaws. So that I can learn from it and better myself on ahead.

**Comment by Harit007x** [comment]
> #137 look at this and only ask to be assigned first, the present solution of yours has many flaws

Please do reply to the above message, it would really help me with my learnings and allow me to improvise.

**Pull request closed without merging**
