### PR TITLE
Custom Job Model + Custom Jobs Form Validation Added

### LINKED ISSUE #42: 📦 [FEATURE]: Add Custom Job Option for enterprises
Many Companies will be interested in contacting us for the following:
- They have lots of posts requirement so they need to discuss discount
- They want to hire through a Hackathon
- They want to hire from people coming to their code base and contributing to it.
- They want to contact us to discuss more hiring ideas/partner with us.

Another site remotejobs.com has these features, while regular job posting is suitable for many ppl, lot of them will be interested in discussing more about it.

for reference- when u click on post a job on remotejobs, u get
image

### PR DESCRIPTION
**Pull request by Pheewww**
Fixes #42 

Added Tabs + Form Validation + Api

[Screen-Recording-2024-08-06T12_43_43.697Z.webm](https://github.com/user-attachments/assets/568c4efd-2628-462a-a635-40d3d81ea744)

### CODE REVIEW

**Comment by Pheewww** [comment]
@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
Can you explain what is regular and custom jobs ?

**Comment by Pheewww** [comment]
Regular jobs are standard job postings that follow a predefined format and are designed for typical job listings, they have fixed prices and sections such as job title, description, requirements, and benefits.

Custom jobs offer more flexibility and can be tailored to specific requirements that go beyond the standard format.
 -They have lots of posts requirement so they need to discuss discount - by 
 -They want to hire through a Hackathon 
 -They want to hire from people coming to their code base and contributing to it.
 -They want to contact us to discuss more hiring ideas/partner with us.
 -They may want to include specific application questions, detailed company culture descriptions, or complex requirements.

In-short, lot of big brands or someone if they want to hire thorugh us and they don't like standard job listing can adopt it.


example - click on post a job on remotejobs.com, there are sponsored/boosted job posts on upwork.

**Comment by VineeTagarwaL-code** [comment]
so the custom job will be the gateway for contact the admins, to put there job out there according to there needs ?

**Comment by Pheewww** [comment]
> so the custom job will be the gateway for contact the admins, to put there job out there according to there needs ?

YES, We can show all the custom jobs on dashboard which maybe like harkirat can see and talk on the requirements

**Comment by VineeTagarwaL-code** [comment]
got it good PR reviewing the code for it

**Comment by Pheewww** [comment]
> got it good PR reviewing the code for it

ok np

**Comment by Pheewww** [comment]
hey @VineeTagarwaL-code any changes?

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that

**Pull request closed without merging**
