### PR TITLE
Make FAQ Sections Clickable 

### PR DESCRIPTION
**Pull request by MisbahAnsar**
Made the entire FAQ section clickable to toggle the answer's visibility
Moved the onClick event and cursor-pointer class to the parent div for each FAQ item
Removed the button element since the click event is now handled by the parent div

BEFORE:

https://github.com/user-attachments/assets/50e7901b-d68f-4690-a254-c12f16ee0864

AFTER:

https://github.com/user-attachments/assets/d75fce56-3cab-43a0-8c3e-6d3b6f592dee

WHY:
bcuz it enhance the user experience and making it easier to expand and collapse FAQs.

### CODE REVIEW

**Comment by MisbahAnsar** [comment]
@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
clean, nice, ati sundar thanks

**Comment by VineeTagarwaL-code** [comment]
also build fails , fix this

**Comment by MisbahAnsar** [comment]
Done @VineeTagarwaL-code 🫡 
i hope it works this time

**Comment by VineeTagarwaL-code** [comment]
hanji sure

**Pull request merged**
