### PR TITLE
Footer Added

### PR DESCRIPTION
**Pull request by AxBwal**
Screenshot 2024-08-07 120350

Footer Added.
Also Link for the twitter , Youtube and the Linkedin added.

### CODE REVIEW

**Comment by AxBwal** [comment]
@VineeTagarwaL-code @SwetanshuSingh

**Comment by AxBwal** [comment]
@VineeTagarwaL-code can You assign the Landing page design to me ....i can work on that

**Comment by VineeTagarwaL-code** [comment]
Go ahead and make the landing page better, also we dont need that much heavy links in the footer minimize it and just add socials for now but try to make it look good

**Comment by AxBwal** [comment]
ok working on the Landing page ,..... and footer Too .... please assign that ..it will much better @VineeTagarwaL-code

**Comment by AxBwal** [comment]
@VineeTagarwaL-code added code please check . framer motion also added

**Comment by VineeTagarwaL-code** [comment]
From next time ask to assigned first rather than opening PR first, although a good pr it includes a lot of things we dont need so not merging for now, thank you for your contribution

**Pull request closed without merging**
