### PR TITLE
feat : redesigned job page

### PR DESCRIPTION
**Pull request by amanbairagi30**
This PR solves #368 

image
image

### CODE REVIEW

**Comment by amanbairagi30** [comment]
@VineeTagarwaL-code 
skills section needs to be added from the create page and then we can show them here in the job page , along with that there are many inconsistencies in UI at /jobs , at landing and  at /create , do let me know if you want me to work upon them .

**Comment by VineeTagarwaL-code** [comment]
the job recommendation should pick the recently posted jobs excluding that he is seeing right now, once done push that change

**Comment by amanbairagi30** [comment]
> the job recommendation should pick the recently posted jobs excluding that he is seeing right now, once done push that change

got it , doing it

**Comment by amanbairagi30** [comment]
@VineeTagarwaL-code , wrote the code for showing the latest 3 jobs (as per the category of the already open job) , if this doesn't match any jobs then we are showing the latest 3 jobs from other categories.

https://github.com/user-attachments/assets/0120c1f2-82a3-400f-a783-0c0744969cf8

**Comment by amanbairagi30** [comment]
@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
build fails

**Comment by amanbairagi30** [comment]
Checking it

**Comment by amanbairagi30** [comment]
build is fixed @VineeTagarwaL-code

**Pull request merged**
