### PR TITLE
Fixed: #393 - UI is not responsive for post a job page

### LINKED ISSUE #393: 🐛 Bug Report: UI is not responsive for post a job page
### 📜 Description

UI is not responsive for post a job page

### 👟 Reproduction steps

go to create a job post on mobile

### 👍 Expected behavior

It should be responsive

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/fb677c38-ba4c-43be-9ca3-ad7d3a3d77be

### OS name

Windows

### browser name

Chrome

### npm version

_No response_

### node version

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by MeerUzairWasHere**
This PR fixes #393 

- Before

https://github.com/user-attachments/assets/d66b2402-a861-46e5-80b3-893ad6bd99e0

- After

https://github.com/user-attachments/assets/e28f58a4-ec18-4c04-b611-71032ec99120

ps: i commented out a line in .husky/pre-commit , it was stopping me for making a commit, please see it accordingly.

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
can you fix these conflicts, will merge after that ?

**Comment by VineeTagarwaL-code** [comment]
it is responsiveness, are you on the latest changes ?

**Comment by MeerUzairWasHere** [comment]
> it is responsiveness, are you on the latest changes ?

Ah, Thir PR is bit old, I'll remove conflicts later. but I don't know what is wrong with linting. it fails and It doesn't allow me to commit, I commented out that line which stopped me to commit.

**Comment by MeerUzairWasHere** [comment]
> can you fix these conflicts, will merge after that ?

Added new PR #407 , You can close this one.

**Pull request closed without merging**
