### PR TITLE
fixed ui issues

### PR DESCRIPTION
**Pull request by Dhirajsingh212**
fix: #459 
Improved the testimonials card ui issue.

Before:
Screenshot from 2024-10-05 20-02-55

After:

https://github.com/user-attachments/assets/9a56ba3f-8cdf-47d7-b5f0-a678253a53ff

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
cant see the video

**Comment by Dhirajsingh212** [comment]
Screenshot from 2024-10-06 20-32-38

Here is the screenshort let me know if it is not visible.

**Comment by VineeTagarwaL-code** [comment]
i want to the see the fallback component height

**Comment by Dhirajsingh212** [comment]
Fixed the height @VineeTagarwaL-code 
Screenshot from 2024-10-06 22-03-27

**Pull request closed without merging**
