### PR TITLE
Improvement : Improved job page UI #Issue no 303

### PR DESCRIPTION
**Pull request by Dark7177**
Improved the job page and added basic edge test cases in it #303 

• Improved the UI using the minimalistic black, grey and blue color combination
• Added drop shadow effect on hover over the job card
• Added basic edge cases to the job file that can be worked upon

Let me know if any further improvements are required

Screenshot (4)

### CODE REVIEW

**Comment by aspired2001** [comment]
I can solve this issue 
Please assign this issue to me sir

**Comment by VineeTagarwaL-code** [comment]
can be improved more, tbh doesnt looks that attractive

**Comment by VineeTagarwaL-code** [comment]
if you can improve over this, it will be good

**Comment by Dark7177** [comment]
> if you can improve over this, it will be good

Okay sir Will be done by tomorrow evening

**Comment by Dark7177** [comment]
image
image

@VineeTagarwaL-code Sir is this any good from previous one's need rough idea about what is needed though ...

**Comment by Dark7177** [comment]
Give me confirmation if it the improvements suits......will update the pr one's confirmed

**Comment by VineeTagarwaL-code** [comment]
not good, will reopen the issue with new figma design

**Pull request closed without merging**
