### PR TITLE
[FEATURE]: Dynamic job form with custom fields

### PR DESCRIPTION
**Pull request by SwetanshuSingh**
1. This PR attempts to enhance the previous job form and adds dynamic data fields for salary based on the currency.
3. It also adds new zod validation rules to support the state and country fields.
4. Adds dynamic form fields which state and country which are available if the location is Hybrid or Office
5. This PR also removes a lot of boiler plate code from react-hook-form by introducing a Custom Input component.

image

Reference - #58

### CODE REVIEW

**Comment by vibhaw1904** [comment]
Hey @SwetanshuSingh ,
I think we should add a field called "Job Type" to indicate whether the job is an internship or full-time. Just a thought for improvement.

**Comment by SwetanshuSingh** [comment]
> Hey @SwetanshuSingh , I think we should add a field called "Job Type" to indicate whether the job is an internship or full-time. Just a thought for improvement.

Yes, j

> Hey @SwetanshuSingh , I think we should add a field called "Job Type" to indicate whether the job is an internship or full-time. Just a thought for improvement.

makes sense, will do that.

**Comment by VineeTagarwaL-code** [comment]
Give a video refrence of workings here, so i can look at it and give my views thank you !

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that

**Pull request closed without merging**
