### PR TITLE
Add Function to Display Job Posting Time

### PR DESCRIPTION
**Pull request by Satyam3245**
Implemented a new function that displays the time elapsed since a job was posted. Enhanced the user experience by providing real-time feedback on job postings in all pages where the job is shown 
Hi @VineeTagarwaL-code 
I've implemented the feature as discussed. The new function displays the time since a job was posted. Please review and let me know if any further adjustments are needed.

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
build fails and conflicts, fix @Satyam3245

**Comment by Satyam3245** [comment]
@VineeTagarwaL-code  i resolve the conflicts  from my side

**Comment by VineeTagarwaL-code** [comment]
build failed

**Comment by pratiiikkk** [comment]
@VineeTagarwaL-code  @Satyam3245 
in this merged pr  #269(landing page redesign )   i already created a function  (calculateTimeSincePosted) using dayjs library  at  job-landing.tsx  also exported it

**Comment by Satyam3245** [comment]
@pratiiikkk @VineeTagarwaL-code do not use an external library for just a simple code that does a simple work

**Comment by pratiiikkk** [comment]
@Satyam3245  I understand your concern about using external libraries for simple tasks. However, using dayjs helps ensure accurate and consistent date manipulation across the project, especially when dealing with time zones, relative time, and formatting. It also reduces the chances of bugs from manual calculations

**Comment by VineeTagarwaL-code** [comment]
build fails, fix please

**Comment by VineeTagarwaL-code** [comment]
closing this inactive pr will open a new issue for this, thanks

**Pull request closed without merging**
