### PR TITLE
[FIXED] #70 [Created a view details overlay] on clicking view details

### PR DESCRIPTION
**Pull request by Shubham-Kumar1**
[fix] #70 

Here's a more natural summary:

In `actions/job.ts`, error handling and messages were improved, and salary range validation was added. 

The `JobCard` component in `components/JobCard.tsx` was updated to manage modals and cleaned up to remove redundant code.

A new `JobDetails` component was added in `components/JobDetails.tsx` to show detailed job information and an "Apply" button.

In `components/Modal.tsx`, modal transitions were refined, accessibility was improved, and scroll issues were fixed.

Screenshot 2024-08-07 at 2 01 28 PM

https://github.com/user-attachments/assets/ffeccf6c-377f-42e4-b0c2-14983a2a184d

### CODE REVIEW

**Review by VineeTagarwaL-code — COMMENTED** [review]
i have viewed all the files, code looks good, will test it locally first then will merge if everything feels good

**Comment by Shubham-Kumar1** [comment]
@VineeTagarwaL-code Got it. I'll make sure to get assigned before working on issues next time. Thanks for the feedback.

**Comment by Shubham-Kumar1** [comment]
- updated replica exactly like remotejobs.com

Screenshot 2024-08-07 at 11 10 44 PM

**Comment by VineeTagarwaL-code** [comment]
https://github.com/code100x/job-board/issues/137 check this by the time, will look onto after this is resolved

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that

**Pull request closed without merging**
