### PR TITLE
added toaster

### PR DESCRIPTION
**Pull request by vatan45**
issue: #437 

added A little toaster that says "coming soon" when clicked on manage profile on the profile dropdown

### CODE REVIEW

**Comment by vatan45** [comment]
@VineeTagarwaL-code  review please

**Comment by aakash2330** [comment]
we already have a toast component , can you use that instead ?

**Comment by vatan45** [comment]
> we already have a toast component , can you use that instead ?

Sure

**Comment by vatan45** [comment]
@VineeTagarwaL-code used the already present toaster, please review

**Pull request merged**
