### PR TITLE
Fix Pagination error

### LINKED ISSUE #220: 🐛 Bug Report: Pagination bug, goes from 1 to 11 on clicking next
### 📜 Description

When you are on a page url like this `http://localhost:3000/jobs?page=2&sortby=postedat_desc` and click on `Next` button, then you will go to page url `http://localhost:3000/jobs?page=21&sortby=postedat_desc`. But, you should have moved to `http://localhost:3000/jobs?page=3&sortby=postedat_desc`.

### 👟 Reproduction steps

1. Click on `Explore` button.
2. Click `Next`.
3. You will move to page=2.
4. Again click on `Next`.
5. You will move to page=21
6. Click on page no. `1` of pagination items.
7. You will move to page=1
8. Click on `Next`
9. You will move to page=11

### 👍 Expected behavior

On clicking `Next`, it should move the page from page=1 to page=2 to page=3 and so on. Basically, increment page by 1.

### 👎 Actual Behavior with Screenshots

Proof:-

https://github.com/user-attachments/assets/9cb2ccf8-2479-4784-a27a-e6d07e466521

### OS name

Windows

### browser name

Brave

### npm version

_No response_

### node version

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by prateekkumaroriginal**
Fix #220 . Pagination works correctly now.

Demo:-

https://github.com/user-attachments/assets/457df279-a106-4d7f-aaa8-567826af80ec

### CODE REVIEW

**Comment by prateekkumaroriginal** [comment]
@VineeTagarwaL-code Please check

**Comment by VineeTagarwaL-code** [comment]
fix the conflicts and we will be good to go

**Comment by prateekkumaroriginal** [comment]
@VineeTagarwaL-code Resolved conflicts.

**Comment by VineeTagarwaL-code** [comment]
Nice work

**Pull request merged**
