### PR TITLE
Fix Landing Page

### LINKED ISSUE #47: ⭐ [IMPROVEMENT]  : Landing Page Design upgrade
# Enhance Homepage Design with Centered Content, Improved Footer, and Framer Motion Animations

## Description
We need to improve the overall design of our homepage to make it more visually appealing. The current design leaves too much empty space, and the footer needs enhancement. Additionally, we should add animations using Framer Motion to bring more life to the page.

## Tasks
1. **Center the content**:
    - Ensure the content remains responsive and looks good on various screen sizes.

2. **Fill the empty space**:
    - Add a background pattern or gradient to the page to make it visually appealing.
    - Consider adding subtle decorative elements to the background.

3. **Enhance the footer**:
    - Improve the footer design with better typography and layout.
    - Add social media icons with links, make it look good
    - Ensure the footer design is consistent with the overall theme of the page.

4. **Add animations using Framer Motion**:
    - Implement smooth animations for the main content as it loads.
    - Add interactive animations to buttons and links.
    - Ensure animations are subtle and enhance the user experience without being distracting.

## Additional Context
- Current design screenshot is attached for reference.
- Ensure all new design elements are consistent with our brand guidelines.
- Test the new design on various devices and screen sizes to ensure responsiveness.

## Pull Request Context
This issue will be handled on a first-come, first-serve basis. We will not assign or lock this issue to any specific contributor. The pull request (PR) that comprehensively addresses all the listed tasks and ensures that every aspect is completed will be reviewed and merged.

- Please make sure to reference this issue in your PR.
- Ensure your changes are well-tested and do not introduce any new issues.
- Include screenshots or screen recordings of the updated design.
- Follow our contribution guidelines and code style.

Good luck, and thank you for your contribution!
## Current Design
image

### PR DESCRIPTION
**Pull request by Pheewww**
Fixes #47 

https://github.com/user-attachments/assets/4d2e05bf-0738-46de-8fd8-c4587e9747a0

components load
[RecordRTC-202477-1m7j1251hwybdd43eu4k.webm](https://github.com/user-attachments/assets/eb103e64-bd27-403f-9787-480ede25d1e7)

### CODE REVIEW

**Comment by Pheewww** [comment]
@VineeTagarwaL-code your thoughts?

**Comment by Pheewww** [comment]
> your thoughts @VineeTagarwaL-code ?

**Comment by Pheewww** [comment]
@VineeTagarwaL-code ek baar review dedo, it was the first req also.

**Comment by VineeTagarwaL-code** [comment]
Pr already merged for this, thanks for your PR

**Pull request closed without merging**
