### PR TITLE
Feat/Added drag-to-scroll functionality for Testimonials section

### PR DESCRIPTION
**Pull request by Harsh8089**
https://github.com/user-attachments/assets/565cc594-bf87-40d4-a5d9-8b804811dbde

### CODE REVIEW

**Comment by Harsh8089** [comment]
@VineeTagarwaL-code please review it.

**Comment by VineeTagarwaL-code** [comment]
Make sure you post on x, OS helps a lot while landing jobs ! :rocket:

**Comment by VineeTagarwaL-code** [comment]
the code can be improved, but works as you are first time contributor i will merge it :rock:

**Comment by Harsh8089** [comment]
> the code can be improved, but works as you are first time contributor i will merge it 🪨

How can I improve it more and in what sense .. implementation wise / UX wise ?

**Pull request merged**
