### PR TITLE
Refactor UI Elements and Enhance Mobile Responsiveness

### PR DESCRIPTION
**Pull request by shaurya35**
- > `Reworked` on Navbar and Main Component and Optimized for devices

https://github.com/user-attachments/assets/75ff7291-611c-41dd-ad15-c4a868e045f4

https://github.com/user-attachments/assets/3970adae-b7b1-40dd-ad9a-1b5bc524dc3d

- > `Added` Page Reload on-clicking Logo

https://github.com/user-attachments/assets/860f647c-5643-4a52-80e4-7a7351566694

### CODE REVIEW

**Comment by shaurya35** [comment]
@VineeTagarwaL-code Please Review the pull request and let me know if there is any scope of improvements. Looking forward to making UI more better

**Comment by SwetanshuSingh** [comment]
> * > `Reworked` on Navbar and Main Component and Optimized for devices
> 
>  Optimized.Navbar.and.Main.mp4 
>  Optimized.Navbar.mp4 
> * > `Added` Page Reload on-clicking Logo
> 
>  Page.Reload.mp4

@shaurya35 Please do the required changes once

**Comment by shaurya35** [comment]
@SwetanshuSingh I didn't get you

**Comment by VineeTagarwaL-code** [comment]
The pr is good but there is one more pr opened after you which i think serves the purpose in the best way possible 

https://github.com/code100x/job-board/pull/40

**Pull request closed without merging**
