### PR TITLE
Added twitter testimonials in place of dummy ones

### PR DESCRIPTION
**Pull request by vatan45**
issue no- #396 
BEFORE:-

Screenshot 2024-09-25 at 11 18 03 AM

AFTER:- 
Screenshot 2024-09-25 at 1 35 55 PM

the testimonials are scrollable so that user can see all of them and it doesnot take much space too on the page

added the tweets of 100xdevs , success stories

### CODE REVIEW

**Review by VineeTagarwaL-code — APPROVED** [review]

**Comment by VineeTagarwaL-code** [comment]
a good pr , get redis of blur sides, and arrow, keep auto scrolling and also allow user to scroll both directions

**Comment by vatan45** [comment]
> a good pr , get redis of blur sides, and arrow, keep auto scrolling and also allow user to scroll both directions

go it , on it

**Comment by vatan45** [comment]
@VineeTagarwaL-code 

https://github.com/user-attachments/assets/da057257-23ff-416f-953a-dbb09927d909

[x]- blur side removed
[x]- arrows removed
[x]- auto scrolling
[]- don't know how to all user to scroll left and right with arrow keys?

**Comment by aakash2330** [comment]
Screenshot 2024-09-27 at 1 00 16 PM

1. can you make it take more space on bigger screens
2. the height of the first card in ss is different from the height in 2nd and third , can you give it some min height so it stays consistent .
3 . There carousel when finishes reverses itself , that too in a different speed , can you make it infinite


https://github.com/user-attachments/assets/f58c5f2b-bdb2-42a8-8081-df6da0fc1d75

4. It should also stop on hover in case someone want to stop and watch a video

**Comment by vatan45** [comment]
> Screenshot 2024-09-27 at 1 00 16 PM
>
> 1. can you make it take more space on bigger screens
> 2. the height of the first card in ss is different from the height in 2nd and third , can you give it some min height so it stays consistent .
>    3 . There carousel when finishes reverses itself , that too in a different speed , can you make it infinite
> 
>  Screen.Recording.2024-09-27.at.1.04.24.PM.mov 
> 4. It should also stop on hover in case someone want to stop and watch a video .
> 5. remove unnecessary empty lines for better readibility .

sure , on it

**Comment by vatan45** [comment]
- [x] Set a Minimum Height for the First Card
- [x] Make the Carousel Infinite
- [x] Pause Carousel on Hover
- [x] Improve Code Readability
@VineeTagarwaL-code  done with more changes

**Comment by vatan45** [comment]
@VineeTagarwaL-code @hkirat review please...

**Pull request merged**
