### PR TITLE
Added the husky and prettier for the project

### PR DESCRIPTION
**Pull request by Ameerjafar**
Added husky to the project.

Screenshot 2024-08-06 202843

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code i have added the husky to the project.

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
Husky is not working, can you look at it ( send a video reference first )

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code let me send the reference video.

**Pull request closed without merging**
