### PR TITLE
added confirmation dialog for Logout

### PR DESCRIPTION
**Pull request by pruthviraj7714**
Issue fix : #116 

### Added Alert-Dialog to confirm the Logout. 

Preview: https://github.com/user-attachments/assets/6e417e18-534c-460b-b989-d525c3437f96

### CODE REVIEW

**Comment by pruthviraj7714** [comment]
@VineeTagarwaL-code I improved the UI of dialog box 
check out:
Light Theme : Screenshot (121)
Dark Theme : Screenshot (123)

**Comment by VineeTagarwaL-code** [comment]
the dark theme looks not that good, plus minimize the text keep it simple , short and clean

**Comment by pruthviraj7714** [comment]
@VineeTagarwaL-code I made necessary changes as suggested.
Light Theme:Screenshot (127)
Dark Theme: Screenshot (126)

**Comment by VineeTagarwaL-code** [comment]
doesnt look that good, maybe you can work on the UI more ?

**Comment by VineeTagarwaL-code** [comment]
the ui is not good at all, can you make it simple and clean

**Comment by pruthviraj7714** [comment]
@VineeTagarwaL-code okay sir I will work on it

**Pull request closed without merging**
