### PR TITLE
filtersheet-update

### LINKED ISSUE #196: 🐛 Bug Report: Responsiveness in Explore Page
### 📜 Description

The Explore Page is Not Responsive .

### 👟 Reproduction steps

Explore page ... job Filter component

### 👍 Expected behavior

The job filter Component should be a sidebar in mobile view

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/cd0e3d38-90c2-4af1-96ed-abb2c7e4d14a

### OS name

MacOS

### browser name

Brave

### npm version

_No response_

### node version

_No response_

### 📃 Provide any additional context for the Bug.

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
## Responsive Explore Page
 -   added filter sheet for smaller devices

fixes #196 

https://github.com/user-attachments/assets/90ebdf55-c709-447b-8871-685656434311

### CODE REVIEW

**Comment by Ashutoshpadhi629** [comment]
hey @VineeTagarwaL-code , can you review this ?

**Comment by VineeTagarwaL-code** [comment]
noice

**Comment by VineeTagarwaL-code** [comment]
fix the conflicts, i will merge

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code , I fixed the merge conflicts , sorry for the extra commit , accidentally pushed the old file in hurry .

**Comment by VineeTagarwaL-code** [comment]
image
solve these type errors

**Comment by VineeTagarwaL-code** [comment]
image
fix this

**Comment by Ashutoshpadhi629** [comment]
on it @VineeTagarwaL-code

**Comment by Ashutoshpadhi629** [comment]
Screenshot 2024-09-17 at 1 45 46 AM

https://github.com/user-attachments/assets/277bb447-324f-4394-a025-c702434cc2b8

@VineeTagarwaL-code

**Pull request merged**
