### PR TITLE
feat:added expiry date feature

### PR DESCRIPTION
**Pull request by Paribesh01**
https://github.com/user-attachments/assets/0914bec9-405c-4fe4-b026-f28991c16252

- #482

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
need to make the expiry date field look nice

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code this Works??
Screenshot 2024-10-11 at 10 09 59 PM
Screenshot 2024-10-11 at 10 10 12 PM<

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code this Works ??
Screenshot 2024-10-11 at 10 20 12 PM
Screenshot 2024-10-11 at 10 20 26 PM

**Comment by VineeTagarwaL-code** [comment]
fix the ui will merge, also does this remove the job from the it has been expired ?

**Comment by VineeTagarwaL-code** [comment]
this is very clean uk that right ? i love it

**Comment by VineeTagarwaL-code** [comment]
let me check the funcitoning of it and the code too, then mergeing, great work thanks for your hardwork

**Review by VineeTagarwaL-code — APPROVED** [review]

**Pull request merged**
