### PR TITLE
Feat/company details management page

### PR DESCRIPTION
**Pull request by Paribesh01**
https://github.com/user-attachments/assets/d6980970-5264-4529-8206-fa8cad9b055d

- #430

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
Wohooooo nice

**Comment by VineeTagarwaL-code** [comment]
will review and merge in this weekened ( tomorrow )

**Comment by CuriousCoder00** [comment]
Is there anything else that needs to be added in it? or needs to be changed

**Comment by Paribesh01** [comment]
There are some bugs, working on it

**Comment by VineeTagarwaL-code** [comment]
fix conflict

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code this should work

**Comment by VineeTagarwaL-code** [comment]
give me video ref of your  current status

**Comment by CuriousCoder00** [comment]
continuing from here in #524 as i cannot push my changes to your fork @Paribesh01 
- Fixed some bugs
- added condition for rendering the company details page only after login
- updated fetching of companies

@VineeTagarwaL-code please review the PR

**Comment by VineeTagarwaL-code** [comment]
will wait for the new ui, will ask you to make that here itself

**Pull request closed without merging**
