### PR TITLE
feat: Add auto-assign issue workflow

### PR DESCRIPTION
**Pull request by CuriousCoder00**
fixes: #454 

Add a new workflow file, auto-assign-issue.yml, to automatically assign issues based on comments. The workflow runs when a new comment is created on an issue and checks if the comment body is '/assign'. If so, it checks the current issue assignees and assigns the issue to the commenter if no one is assigned or logs the appropriate message if the issue is already assigned. Finally, it comments on the issue with the outcome of the assignment.

372970709-845e929e-c3ae-4933-88cd-50b6d9462264

### CODE REVIEW

**Comment by CuriousCoder00** [comment]
373268882-dc66a040-f046-4e12-9143-f383a1d4b68c

**Comment by VineeTagarwaL-code** [comment]
can maintainer only assign, i dont want anyone to pick up on its own

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code will make changes for that so only maintainers or user with administration access can assing issue

**Comment by VineeTagarwaL-code** [comment]
but why is this even needed if maintainer will do it anyways ?

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code you're right, however i raised this pr for users to take issue on their own..
If it's not needed will close the pr

**Comment by VineeTagarwaL-code** [comment]
i will be opening a lot of open features and issues today, be tuned

**Comment by CuriousCoder00** [comment]
> i will be opening a lot of open features and issues today, be tuned

@VineeTagarwaL-code Looking forward to it..!!!

**Pull request closed without merging**
