### PR TITLE
Feat: created the bookmark functionality

### LINKED ISSUE #413: 🚀 Feature: Add a "Bookmark" button to job listings.
### 🔖 Feature description

The Job Bookmarking feature allows users to bookmark job listings they are interested in, enabling them to easily revisit and apply later. Users can click a "Bookmark" button on job listings to save them, and these saved jobs will be displayed on the user's dashboard.

### 🎤 Why is this feature needed ?

The Job Bookmarking feature allows users to bookmark job listings they are interested in, enabling them to easily revisit and apply later. Users can click a "Bookmark" button on job listings to save them, and these saved jobs will be displayed on the user's dashboard.

### ✌️ How do you aim to achieve this?

To implement this feature, I will:

1.  Frontend: Add a bookmark button to each job listing. The button will toggle between "Bookmark" and "Remove Bookmark" based on the user's interaction. 

2.  Backend: Create a Prisma model relation between users and jobs to store bookmarked jobs.

3.   API: Develop an endpoint to handle the adding/removing of bookmarks.

4.   Dashboard: Create a section in the user dashboard that lists all bookmarked jobs.

### 🔄️ Additional Information

Alternative solutions could involve using browser storage (like local storage) to temporarily store bookmarks, but this wouldn't persist across devices or sessions. The proposed solution ensures that bookmarks are tied to user accounts, allowing access from any device.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Kashyap1ankit**
@VineeTagarwaL-code  closes #413 

[Screencast from 2024-10-19 16-14-19.webm](https://github.com/user-attachments/assets/ce2f5cb5-1fa2-4568-b2b4-7bb8c2d8eb6f)

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
bug - add bookmark seems slow fix that
2. saved job bookmark button seems to get fetched very slowly
3. bookmark a job -> reload the explore page  -> prev marked job doesn't have the bookmark tag

**Comment by Kashyap1ankit** [comment]
> bug - add bookmark seems slow fix that 2. saved job bookmark button seems to get fetched very slowly 3. bookmark a job -> reload the explore page -> prev marked job doesn't have the bookmark tag


@VineeTagarwaL-code 3. bookmark a job -> reload the explore page -> prev marked job doesn't have the bookmark tag

can you explain this more?

**Comment by VineeTagarwaL-code** [comment]
done in discord dm, any problem if there feel free to dm me again !

**Comment by Kashyap1ankit** [comment]
@VineeTagarwaL-code  resolved the reload bookmark disappear bug and loading issue

[Screencast from 2024-10-20 23-29-51.webm](https://github.com/user-attachments/assets/6eba9266-9806-426d-882f-ff102b9a29e6)

**Pull request merged**
