### PR TITLE
🔧fix: Docker build fails to run

### PR DESCRIPTION
**Pull request by pawann-2000**
fix for #193

### CODE REVIEW

**Comment by VineeTagarwaL-code** [comment]
give video ref of it running

**Comment by pawann-2000** [comment]
Roger, here's a short vid of it running


https://github.com/user-attachments/assets/c7571119-7449-4d7f-bf44-ae1177952a36

**Comment by pawann-2000** [comment]
ignore the above changes, was testing the CI on my local branch

**Comment by VineeTagarwaL-code** [comment]
LGTM !

**Pull request merged**
